apiVersion: eventing.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: backend-memory-sub
spec:
  channel:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: backend-demo-memory
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: knative-event-backend-demo
