apiVersion: eventing.knative.dev/v1alpha1
kind: Channel
metadata:
  name: backend-demo-kafka
spec:
  provisioner:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: ClusterChannelProvisioner
    name: kafka
